apiVersion: tekton.dev/v1beta1
###sdasdfadsfsadfasdf
kind: PipelineRun
metadata:
  name: e2e-on-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: "quay.io/redhat-appstudio/pull-request-builds:e2e-{{revision}}"
  pipelineRef:
    name: docker-build
    bundle: quay.io/psturc/hacbs-templates-bundle:2022-09-07-164332
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: app-studio-default-workspace
      subPath: e2e-tests-check-{{ revision }}