apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[pull_request]'
    pipelinesascode.tekton.dev/on-target-branch: '[main,master]'
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: build-suite-test-application-qqph
    appstudio.openshift.io/component: test-component-pac-pegq
    pipelines.appstudio.openshift.io/type: build
  name: test-component-pac-pegq-on-pull-request
  namespace: build-e2e-rwut
spec:
  params:
  - name: git-url
    value: '{{repo_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/psturc/test-images:on-pr-{{revision}}
  - name: dockerfile
    value: docker/Dockerfile
  - name: path-context
    value: .
  pipelineSpec:
    finally:
    - name: show-summary
      params:
      - name: pipeline-run-name
        value: $(context.pipelineRun.name)
      - name: git-url
        value: $(params.git-url)
      - name: image-url
        value: $(params.output-image)
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-2
        name: summary
    - name: hacbs-test-evaluation
      params:
      - name: BASE_IMAGE
        value: $(tasks.sanity-inspect-image.results.BASE_IMAGE)
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-1
        name: hacbs-test-evaluation
      workspaces:
      - name: workspace
        workspace: workspace
    params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    - description: Fully Qualified Output Image
      name: output-image
      type: string
    - default: .
      description: The path to your source code
      name: path-context
      type: string
    - default: Dockerfile
      description: Path to the Dockerfile
      name: dockerfile
      type: string
    - default: "true"
      description: Force rebuild image
      name: rebuild
      type: string
    results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.build-container.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.clone-repository.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.clone-repository.results.commit)
    tasks:
    - name: appstudio-init
      params:
      - name: image-url
        value: $(params.output-image)
      - name: rebuild
        value: $(params.rebuild)
      - name: jvm-build-service-init
        value: "true"
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-1
        name: init
    - name: clone-repository
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.revision)
      runAfter:
      - appstudio-init
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-1
        name: git-clone
      when:
      - input: $(tasks.appstudio-init.results.build)
        operator: in
        values:
        - "true"
      workspaces:
      - name: output
        workspace: workspace
      - name: basic-auth
        workspace: git-auth
    - name: appstudio-configure-build
      runAfter:
      - clone-repository
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-1
        name: configure-build
      when:
      - input: $(tasks.appstudio-init.results.build)
        operator: in
        values:
        - "true"
      workspaces:
      - name: source
        workspace: workspace
      - name: registry-auth
        workspace: registry-auth
    - name: build-container
      params:
      - name: IMAGE
        value: $(params.output-image)
      - name: DOCKERFILE
        value: $(params.dockerfile)
      - name: CONTEXT
        value: $(params.path-context)
      - name: BUILD_EXTRA_ARGS
        value: $(tasks.appstudio-configure-build.results.buildah-auth-param)
      - name: PUSH_EXTRA_ARGS
        value: $(tasks.appstudio-configure-build.results.buildah-auth-param)
      - name: MAVEN_MIRROR_URL
        value: http://localhost:2000/maven2
      runAfter:
      - appstudio-configure-build
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-1
        name: buildah
      when:
      - input: $(tasks.appstudio-init.results.build)
        operator: in
        values:
        - "true"
      workspaces:
      - name: source
        workspace: workspace
    - name: sanity-inspect-image
      params:
      - name: IMAGE_URL
        value: $(params.output-image)
      runAfter:
      - build-container
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-2
        name: sanity-inspect-image
      workspaces:
      - name: workspace
        workspace: workspace
    - name: sanity-label-check
      runAfter:
      - sanity-inspect-image
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-2
        name: sanity-label-check
      workspaces:
      - name: workspace
        workspace: workspace
    - name: sanity-optional-label-check
      params:
      - name: POLICY_NAMESPACE
        value: optional_checks
      runAfter:
      - sanity-inspect-image
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-2
        name: sanity-label-check
      workspaces:
      - name: workspace
        workspace: workspace
    - name: deprecated-base-image-check
      params:
      - name: IMAGE_REGISTRY
        value: registry.access.redhat.com
      - name: IMAGE_REPOSITORY
        value: $(tasks.sanity-inspect-image.results.BASE_IMAGE_REPOSITORY)
      runAfter:
      - sanity-inspect-image
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-1
        name: deprecated-image-check
      workspaces:
      - name: sanity-ws
        workspace: workspace
    - name: get-clair-results
      params:
      - name: image-digest
        value: $(tasks.build-container.results.IMAGE_DIGEST)
      - name: image-url
        value: $(tasks.build-container.results.IMAGE_URL)
      runAfter:
      - build-container
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-1
        name: get-clair-scan
      workspaces:
      - name: clair-ws
        workspace: workspace
      - name: registry-auth
        workspace: registry-auth
    - name: conftest-clair
      runAfter:
      - get-clair-results
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-1
        name: conftest-clair
      workspaces:
      - name: conftest-ws
        workspace: workspace
    - name: sast-go
      runAfter:
      - build-container
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-2
        name: sast-go
      workspaces:
      - name: workspace
        workspace: workspace
    - name: sast-java-sec-check
      params:
      - name: PATH_CONTEXT
        value: $(params.path-context)
      runAfter:
      - build-container
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-2
        name: sast-java-sec-check
      workspaces:
      - name: workspace
        workspace: workspace
    - name: sast-snyk-check
      runAfter:
      - clone-repository
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-2
        name: sast-snyk-check
      workspaces:
      - name: workspace
        workspace: workspace
    - name: clamav-scan
      params:
      - name: image-digest
        value: $(tasks.build-container.results.IMAGE_DIGEST)
      - name: image-url
        value: $(tasks.build-container.results.IMAGE_URL)
      runAfter:
      - build-container
      taskRef:
        bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-1
        name: clamav-scan
      workspaces:
      - name: registry-auth
        workspace: registry-auth
    workspaces:
    - name: workspace
    - name: registry-auth
      optional: true
    - name: git-auth
      optional: true
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: registry-auth
    secret:
      secretName: redhat-appstudio-registry-pull-secret
status: {}
